# Generated by Django 3.2.8 on 2021-10-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mms',
            name='mms_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mms',
            name='mms_200',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mms',
            name='mms_50',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
